---

# Project information
site_name: fullstack-devops | Docs
site_description: Docs for the fullstack-devops community
site_author: The fullstack-devops project
site_url: https://fullstack-devops.github.io/

# Repository
repo_name: fullstack-devops/fullstack-devops.github.io
repo_url: https://github.com/fullstack-devops/fullstack-devops.github.io
edit_uri: ""

# Configuration
theme:
  name: material
  logo: https://raw.githubusercontent.com/fullstack-devops/organization/main/logo/fullstack-devops-32.png
  favicon: https://raw.githubusercontent.com/fullstack-devops/organization/main/logo/fullstack-devops-32.png
  icon:
    repo: fontawesome/brands/github-alt
  language: en
  features:
    - navigation.sections
    - navigation.tabs
    - navigation.tracking
    # - navigation.indexes
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

docs_dir: ./docs

extra_css:
  - _static/custom.css

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
  - redirects:
      redirect_maps:
        helm-charts/getting-started.md: helm-charts/introduction.md

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fullstack-devops

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: k8s-at-home
      repo: docs
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  # - Helm Charts:
  #     - Introduction: helm-charts/introduction.md
  #     - Common: helm-charts/common-library.md
  #     - Common Storage: helm-charts/common-library-storage.md
  #     - Common Add-ons: helm-charts/common-library-add-ons.md
  #     - Development:
  #         - Creating a new chart: helm-charts/development/creating-a-new-chart.md
  #         - Databases: our-helm-charts/development/databases.md
  #         - Unit tests: our-helm-charts/development/unit-tests.md
  # - Our Container Images:
  #     - Introduction: our-container-images/introduction.md
  #     - Configuration: our-container-images/configuration.md
  #     - Permissions: our-container-images/permissions.md
  #     - Development:
  #         - Creating a new container image: >-
  #             our-container-images/development/creating-a-new-container-image.md
  #         - Dockerfile: our-container-images/development/dockerfile.md
  #         - Base images: our-container-images/development/base-images.md
  #         - Build: our-container-images/development/build.md
  # - Our Code Projects:
  #     - Introduction: our-own-code-projects/introduction.md
  #     - Development:
  #         - Creating a new project: >-
  #             our-own-code-projects/development/creating-a-new-container-image.md
  # - Guides:
  #     - DynDNS with a CronJob: guides/dyndns.md
  #     - Routing traffic through a VPN pod: guides/pod-gateway.md
  #     - Updating Sonarr/Radarr with Recyclarr: guides/recyclarr.md
  # - Support:
  #     - Community: support/community.md
  #     - FAQ: support/faq.md
  #     - Code of Conduct: support/code-of-conduct.md