contact_links:
  - name: Question 🙋‍♀️
    url: https://github.com/h-enk/doks/discussions/categories/q-a
    about: Ask your question in Fs-DevOps Discussions
  - name: Ideas 🤔
    url: https://github.com/orgs/fullstack-devops/discussions/categories/q-a
    about: Share your ideas in Fs-DevOps Discussions
