apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    {{- include "github-actions-runner.labels" . | nindent 4 }}
type: Opaque
data:
  GH_ACCESS_TOKEN: {{ .Values.runner.github.accessToken | b64enc | squote }}
