name: Publish docs via GitHub Pages

concurrency: release-docs

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Synchronize submodules"]
    types:
      - completed
  push:
    branches:
    - 'docs-*'
    - main
    paths:
    - '.github/workflows/docs.yml'
    - 'mkdocs.yaml'
    - 'docs/**'

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.fork == false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Configure Git
        run: |
          git config user.name "fullstack-devops[bot]"
          git config user.email "fullstack-devops[bot]@users.noreply.github.com"
      - run: |
          pip install -r requirements.txt
      - run: mkdocs gh-deploy --config-file ./mkdocs.yml --force
